# Generated by Django 6.0 on 2026-01-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('from_org', models.CharField(max_length=255)),
                ('to_org', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('internal', 'ภายใน'), ('external', 'ภายนอก')], max_length=10)),
                ('secret_level', models.CharField(choices=[('normal', 'ปกติ'), ('secret', 'ลับ'), ('verysecret', 'ลับมาก'), ('topsecret', 'ลับที่สุด')], max_length=12)),
                ('urgency', models.CharField(choices=[('normal', 'ปกติ'), ('urgent', 'ด่วน'), ('veryurgent', 'ด่วนมาก'), ('topurgent', 'ด่วนที่สุด')], max_length=12)),
                ('officer', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
