# Generated by Django 6.0.2 on 2026-02-24 11:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('from_org', models.CharField(blank=True, max_length=255)),
                ('to_org', models.CharField(blank=True, max_length=255)),
                ('officer', models.CharField(blank=True, max_length=100)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('is_accepted', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('internal', 'ภายใน'), ('external', 'ภายนอก')], default='internal', max_length=10)),
                ('secret_level', models.CharField(choices=[('normal', 'ปกติ'), ('secret', 'ลับ'), ('verysecret', 'ลับมาก'), ('topsecret', 'ลับที่สุด')], default='normal', max_length=12)),
                ('urgency', models.CharField(choices=[('normal', 'ปกติ'), ('urgent', 'ด่วน'), ('veryurgent', 'ด่วนมาก'), ('topurgent', 'ด่วนที่สุด')], default='normal', max_length=12)),
                ('remark', models.TextField(blank=True)),
                ('file', models.FileField(null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('waiting', 'รอผอ.พิจารณา'), ('signed', 'ผอ.ลงนามแล้ว'), ('forwarded', 'ส่งต่อแผนกแล้ว')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_department', models.CharField(blank=True, max_length=100)),
                ('to_department', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='docs.document')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('received', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.document')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'ผู้ดูแลระบบ'), ('doctor', 'แพทย์'), ('nurse', 'พยาบาล/เจ้าหน้าที่'), ('executive', 'ผู้บริหาร')], default='nurse', max_length=20, verbose_name='บทบาท')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('pos_x', models.FloatField(default=100)),
                ('pos_y', models.FloatField(default=100)),
                ('page_number', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='docs.document')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'signer')},
            },
        ),
    ]
