# Generated by Django 6.0.2 on 2026-03-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'ผู้ดูแลระบบ'), ('staff', 'เจ้าหน้าที่'), ('director', 'ผู้อำนวยการ')], default='staff', max_length=20, verbose_name='บทบาท'),
        ),
    ]
