# Generated by Django 6.0.1 on 2026-01-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_department_documentflow_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='sender',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
